<?php
/**
 * Testimonial — Style 1
 * Variables: $testimonials, $slider_speed, $slides_per_view,
 *            $slides_per_view_tablet, $slides_per_view_mobile,
 *            $nav_position, $nav_type
 */

$widget_id   = $this->get_id();
$total       = count( $testimonials );
$per_desktop = max( 1, min( 5, (int) $slides_per_view ) );
$per_tablet  = max( 1, min( 5, (int) $slides_per_view_tablet ) );
$per_mobile  = max( 1, min( 3, (int) $slides_per_view_mobile ) );
$wrapper_id  = 'trad-ts1-' . esc_attr( $widget_id );
$nav_pos     = ( isset( $nav_position ) && $nav_position === 'above' ) ? 'above' : 'below';
$nav_t       = isset( $nav_type ) ? $nav_type : 'arrows';
$show_arrows = in_array( $nav_t, [ 'arrows', 'both' ], true );
$show_dots   = in_array( $nav_t, [ 'dots',   'both' ], true );

// Hardcoded SVG icons
$quote_svg = '<svg width="1em" height="1em" viewBox="0 0 40 30" fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M0 30V18.75C0 13.75 1.45833 9.58333 4.375 6.25C7.29167 2.91667 11.25 0.833333 16.25 0V5C13.5833 5.83333 11.4583 7.22917 9.875 9.1875C8.29167 11.1458 7.5 13.4583 7.5 16.125V17.5H15V30H0ZM22.5 30V18.75C22.5 13.75 23.9583 9.58333 26.875 6.25C29.7917 2.91667 33.75 0.833333 38.75 0V5C36.0833 5.83333 33.9583 7.22917 32.375 9.1875C30.7917 11.1458 30 13.4583 30 16.125V17.5H37.5V30H22.5Z"/></svg>';
$prev_svg   = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="15 18 9 12 15 6"></polyline></svg>';
$next_svg   = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="9 18 15 12 9 6"></polyline></svg>';

// Build nav blocks
ob_start(); ?>
<div class="trad-ts1-nav">
    <button class="trad-ts1-arrow trad-ts1-prev" aria-label="<?php esc_attr_e( 'Previous', 'turbo-addons-elementor-pro' ); ?>">
        <?php echo $prev_svg; ?>
    </button>
    <button class="trad-ts1-arrow trad-ts1-next" aria-label="<?php esc_attr_e( 'Next', 'turbo-addons-elementor-pro' ); ?>">
        <?php echo $next_svg; ?>
    </button>
</div>
<?php $arrows_html = ob_get_clean();

ob_start(); ?>
<div class="trad-ts1-dots">
    <!-- dots generated by JS based on perView -->
</div>
<?php $dots_html = ob_get_clean(); ?>

<div
    class="trad-ts1-wrapper"
    id="<?php echo esc_attr( $wrapper_id ); ?>"
    data-speed="<?php echo esc_attr( $slider_speed ); ?>"
    data-per-desktop="<?php echo esc_attr( $per_desktop ); ?>"
    data-per-tablet="<?php echo esc_attr( $per_tablet ); ?>"
    data-per-mobile="<?php echo esc_attr( $per_mobile ); ?>"
>
    <?php if ( $nav_pos === 'above' ) : ?>
        <?php if ( $show_arrows ) echo $arrows_html; ?>
        <?php if ( $show_dots   ) echo $dots_html;   ?>
    <?php endif; ?>

    <div class="trad-ts1-track-outer">
        <div class="trad-ts1-track">
            <?php foreach ( $testimonials as $index => $item ) :
                $image_url   = ! empty( $item['testimonial_image']['url'] )    ? $item['testimonial_image']['url']    : '';
                $name        = ! empty( $item['testimonial_name'] )            ? $item['testimonial_name']            : '';
                $designation = ! empty( $item['testimonial_designation'] )     ? $item['testimonial_designation']     : '';
                $content     = ! empty( $item['testimonial_content'] )         ? $item['testimonial_content']         : '';
            ?>
            <div class="trad-ts1-slide">
                <div class="trad-ts1-card">
                    <div class="trad-ts1-card-top">
                        <?php if ( $image_url ) : ?>
                        <img class="trad-ts1-author-img" src="<?php echo esc_url( $image_url ); ?>" alt="<?php echo esc_attr( $name ); ?>">
                        <?php else : ?>
                        <div class="trad-ts1-author-img trad-ts1-author-placeholder"></div>
                        <?php endif; ?>
                        <span class="trad-ts1-quote-icon"><?php echo $quote_svg; ?></span>
                    </div>
                    <p class="trad-ts1-text"><?php echo esc_html( $content ); ?></p>
                    <div class="trad-ts1-author-footer">
                        <span class="trad-ts1-name"><?php echo esc_html( $name ) ; ?></span> 
                        <?php if ( $designation ) : ?>
                        <!-- <span class="trad-ts1-sep"> &ndash; </span> -->
                        <span class="trad-ts1-designation"><?php echo esc_html( $designation ); ?></span>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>

    <?php if ( $nav_pos === 'below' ) : ?>
        <?php if ( $show_arrows ) echo $arrows_html; ?>
        <?php if ( $show_dots   ) echo $dots_html;   ?>
    <?php endif; ?>
</div>

<script>
(function () {
    'use strict';
    var wrapId = '<?php echo esc_js( $wrapper_id ); ?>';

    function getPerView(wrap) {
        var w = window.innerWidth;
        if (w <= 767)  return parseInt(wrap.getAttribute('data-per-mobile'),  10) || 1;
        if (w <= 1024) return parseInt(wrap.getAttribute('data-per-tablet'),  10) || 2;
        return parseInt(wrap.getAttribute('data-per-desktop'), 10) || 2;
    }

    function initTS1(wrap) {
        if (!wrap || wrap._ts1Inited) return;
        wrap._ts1Inited = true;

        var track    = wrap.querySelector('.trad-ts1-track');
        var slides   = wrap.querySelectorAll('.trad-ts1-slide');
        var btnPrev  = wrap.querySelector('.trad-ts1-prev');
        var btnNext  = wrap.querySelector('.trad-ts1-next');
        var dotsWrap = wrap.querySelector('.trad-ts1-dots');
        var total    = slides.length;
        var speed    = parseInt(wrap.getAttribute('data-speed'), 10) || 4000;
        var current  = 0;
        var maxIndex = 0;
        var autoTimer = null, resizeTimer = null;

        // Build correct number of dots: maxIndex + 1 = total - perView + 1
        function buildDots() {
            if (!dotsWrap) return;
            var pv      = getPerView(wrap);
            var dotCount = Math.max(1, total - pv + 1);
            dotsWrap.innerHTML = '';
            for (var i = 0; i < dotCount; i++) {
                var btn = document.createElement('button');
                btn.className = 'trad-ts1-dot' + (i === current ? ' trad-ts1-dot-active' : '');
                btn.setAttribute('data-index', i);
                btn.setAttribute('aria-label', 'Slide ' + (i + 1));
                (function (idx) {
                    btn.addEventListener('click', function () {
                        goTo(idx);
                        stopAuto(); startAuto();
                    });
                }(i));
                dotsWrap.appendChild(btn);
            }
        }

        function updateDots(idx) {
            if (!dotsWrap) return;
            var allDots = dotsWrap.querySelectorAll('.trad-ts1-dot');
            allDots.forEach(function (d, i) { d.classList.toggle('trad-ts1-dot-active', i === idx); });
        }

        function applyWidths() {
            var pv = getPerView(wrap);
            maxIndex = Math.max(0, total - pv);
            var sw = wrap.querySelector('.trad-ts1-track-outer').offsetWidth / pv;
            slides.forEach(function (s) { s.style.width = s.style.minWidth = s.style.maxWidth = sw + 'px'; });
            if (current > maxIndex) current = maxIndex;
            track.style.transition = 'none';
            track.style.transform  = 'translateX(' + (-current * sw) + 'px)';
            requestAnimationFrame(function () { track.style.transition = ''; });
            buildDots();
            updateDots(current);
        }

        function goTo(idx) {
            var pv = getPerView(wrap);
            maxIndex = Math.max(0, total - pv);
            current  = Math.max(0, Math.min(idx, maxIndex));
            var sw = wrap.querySelector('.trad-ts1-track-outer').offsetWidth / pv;
            track.style.transform = 'translateX(' + (-current * sw) + 'px)';
            updateDots(current);
        }

        function next() { goTo(current >= maxIndex ? 0 : current + 1); }
        function prev() { goTo(current <= 0 ? maxIndex : current - 1); }
        function startAuto() { stopAuto(); if (speed > 0) autoTimer = setInterval(next, speed); }
        function stopAuto()  { clearInterval(autoTimer); }

        btnNext && btnNext.addEventListener('click', function () { next(); stopAuto(); startAuto(); });
        btnPrev && btnPrev.addEventListener('click', function () { prev(); stopAuto(); startAuto(); });

        window.addEventListener('resize', function () {
            clearTimeout(resizeTimer);
            resizeTimer = setTimeout(applyWidths, 100);
        });
        applyWidths();
        startAuto();
    }

    function boot() {
        var el = document.getElementById(wrapId);
        if (el) { initTS1(el); return; }
        var obs = new MutationObserver(function () {
            var e = document.getElementById(wrapId);
            if (e) { obs.disconnect(); initTS1(e); }
        });
        obs.observe(document.body, { childList: true, subtree: true });
    }
    document.readyState === 'loading' ? document.addEventListener('DOMContentLoaded', boot) : boot();

    if (window.elementorFrontend) {
        window.elementorFrontend.hooks.addAction('frontend/element_ready/trad_testimonial_slider.default', function ($scope) {
            var w = $scope[0] && $scope[0].querySelector('.trad-ts1-wrapper');
            if (w) { w._ts1Inited = false; initTS1(w); }
        });
    }
}());
</script>
