<?php
/**
 * Testimonial — Style 2
 * Variables: $testimonials, $slider_speed, $slides_per_view,
 *            $slides_per_view_tablet, $slides_per_view_mobile,
 *            $nav_position, $nav_type
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
} 


$trad_widget_id   = $this->get_id();
$trad_total       = count( $testimonials );
$trad_per_desktop = max( 1, min( 5, (int) $slides_per_view ) );
$trad_per_tablet  = max( 1, min( 5, (int) $slides_per_view_tablet ) );
$trad_per_mobile  = max( 1, min( 3, (int) $slides_per_view_mobile ) );
$trad_wrapper_id  = 'trad-ts2-' . esc_attr( $trad_widget_id );
$trad_nav_pos     = ( isset( $nav_position ) && $nav_position === 'above' ) ? 'above' : 'below';
$trad_nav_t       = isset( $nav_type ) ? $nav_type : 'dots';
$trad_show_arrows = in_array( $trad_nav_t, [ 'arrows', 'both' ], true );
$trad_show_dots   = in_array( $trad_nav_t, [ 'dots',   'both' ], true );

// Hardcoded SVG icons
$trad_quote_svg = '<svg width="1em" height="1em" viewBox="0 0 40 30" fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M0 30V18.75C0 13.75 1.45833 9.58333 4.375 6.25C7.29167 2.91667 11.25 0.833333 16.25 0V5C13.5833 5.83333 11.4583 7.22917 9.875 9.1875C8.29167 11.1458 7.5 13.4583 7.5 16.125V17.5H15V30H0ZM22.5 30V18.75C22.5 13.75 23.9583 9.58333 26.875 6.25C29.7917 2.91667 33.75 0.833333 38.75 0V5C36.0833 5.83333 33.9583 7.22917 32.375 9.1875C30.7917 11.1458 30 13.4583 30 16.125V17.5H37.5V30H22.5Z"/></svg>';
$trad_prev_svg   = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="15 18 9 12 15 6"></polyline></svg>';
$trad_next_svg   = '<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="9 18 15 12 9 6"></polyline></svg>';

// Build nav blocks
ob_start(); ?>
<div class="trad-ts2-nav">
    <button class="trad-ts2-arrow trad-ts2-prev" aria-label="<?php esc_attr_e( 'Previous', 'freemius-turbo-addons-elementor-pro' ); ?>">
        <?php echo $trad_prev_svg; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- hardcoded SVG ?>
    </button>
    <button class="trad-ts2-arrow trad-ts2-next" aria-label="<?php esc_attr_e( 'Next', 'freemius-turbo-addons-elementor-pro' ); ?>">
        <?php echo $trad_next_svg; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- hardcoded SVG ?>
    </button>
</div>
<?php $trad_arrows_html = ob_get_clean();

ob_start(); ?>
<div class="trad-ts2-dots" role="tablist">
    <!-- dots generated by JS based on perView -->
</div>
<?php $trad_dots_html = ob_get_clean(); ?>

<div
    class="trad-ts2-wrapper"
    id="<?php echo esc_attr( $trad_wrapper_id ); ?>"
    data-speed="<?php echo esc_attr( $slider_speed ); ?>"
    data-per-desktop="<?php echo esc_attr( $trad_per_desktop ); ?>"
    data-per-tablet="<?php echo esc_attr( $trad_per_tablet ); ?>"
    data-per-mobile="<?php echo esc_attr( $trad_per_mobile ); ?>"
    data-total="<?php echo esc_attr( $trad_total ); ?>"
>
    <?php if ( $trad_nav_pos === 'above' ) : ?>
        <?php if ( $trad_show_arrows ) echo $trad_arrows_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- safe buffered HTML ?>
        <?php if ( $trad_show_dots   ) echo $trad_dots_html;   // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- safe buffered HTML ?>
    <?php endif; ?>

    <div class="trad-ts2-track-outer">
        <div class="trad-ts2-track">
            <?php foreach ( $testimonials as $trad_index => $trad_item ) :
                $trad_image_url   = ! empty( $trad_item['testimonial_image']['url'] )    ? $trad_item['testimonial_image']['url']    : '';
                $trad_name        = ! empty( $trad_item['testimonial_name'] )            ? $trad_item['testimonial_name']            : '';
                $trad_designation = ! empty( $trad_item['testimonial_designation'] )     ? $trad_item['testimonial_designation']     : '';
                $trad_content     = ! empty( $trad_item['testimonial_content'] )         ? $trad_item['testimonial_content']         : '';
            ?>
            <div class="trad-ts2-slide" data-index="<?php echo esc_attr( $trad_index ); ?>">
                <div class="trad-ts2-card<?php echo $trad_index === 0 ? ' trad-ts2-card-active' : ''; ?>">
                    <span class="trad-ts2-quote-icon"><?php echo $trad_quote_svg; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- hardcoded SVG ?></span>
                    <p class="trad-ts2-text"><?php echo esc_html( $trad_content ); ?></p>
                    <div class="trad-ts2-author-row">
                        <?php if ( $trad_image_url ) : ?>
                        <img class="trad-ts2-author-img" src="<?php echo esc_url( $trad_image_url ); ?>" alt="<?php echo esc_attr( $trad_name ); ?>">
                        <?php else : ?>
                        <div class="trad-ts2-author-img trad-ts2-author-placeholder"></div>
                        <?php endif; ?>
                        <div class="trad-ts2-author-info">
                            <span class="trad-ts2-name"><?php echo esc_html( $trad_name ); ?></span>
                            <?php if ( $trad_designation ) : ?>
                            <span class="trad-ts2-designation"><?php echo esc_html( $trad_designation ); ?></span>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>

    <?php if ( $trad_nav_pos === 'below' ) : ?>
        <?php if ( $trad_show_arrows ) echo $trad_arrows_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- safe buffered HTML ?>
        <?php if ( $trad_show_dots   ) echo $trad_dots_html;   // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- safe buffered HTML ?>
    <?php endif; ?>
</div>

<script>
(function () {
    'use strict';
    var wrapId = '<?php echo esc_js( $trad_wrapper_id ); ?>';

    function getPerView(wrap) {
        var w = window.innerWidth;
        if (w <= 767)  return parseInt(wrap.getAttribute('data-per-mobile'),  10) || 1;
        if (w <= 1024) return parseInt(wrap.getAttribute('data-per-tablet'),  10) || 2;
        return parseInt(wrap.getAttribute('data-per-desktop'), 10) || 3;
    }

    function initTS2(wrap) {
        if (!wrap || wrap._ts2Inited) return;
        wrap._ts2Inited = true;

        var track    = wrap.querySelector('.trad-ts2-track');
        var slides   = wrap.querySelectorAll('.trad-ts2-slide');
        var cards    = wrap.querySelectorAll('.trad-ts2-card');
        var dotsWrap = wrap.querySelector('.trad-ts2-dots');
        var btnPrev  = wrap.querySelector('.trad-ts2-prev');
        var btnNext  = wrap.querySelector('.trad-ts2-next');
        var total    = slides.length;
        var speed    = parseInt(wrap.getAttribute('data-speed'), 10) || 4000;
        var current  = 0;
        var maxIdx   = 0;
        var autoTimer = null, resizeTimer = null;

        // Build correct number of dots: total - perView + 1
        function buildDots() {
            if (!dotsWrap) return;
            var pv       = getPerView(wrap);
            var dotCount = Math.max(1, total - pv + 1);
            dotsWrap.innerHTML = '';
            for (var i = 0; i < dotCount; i++) {
                var btn = document.createElement('button');
                btn.className = 'trad-ts2-dot' + (i === current ? ' trad-ts2-active' : '');
                btn.setAttribute('data-index', i);
                btn.setAttribute('role', 'tab');
                btn.setAttribute('aria-label', 'Slide ' + (i + 1));
                (function (idx) {
                    btn.addEventListener('click', function () {
                        goTo(idx);
                        stopAuto(); startAuto();
                    });
                }(i));
                dotsWrap.appendChild(btn);
            }
        }

        function updateDots(idx) {
            if (!dotsWrap) return;
            dotsWrap.querySelectorAll('.trad-ts2-dot').forEach(function (d, i) {
                d.classList.toggle('trad-ts2-active', i === idx);
            });
        }

        function updateActiveCard(idx) {
            var pv = getPerView(wrap);
            var ci = (pv === 1) ? idx : idx + Math.floor(pv / 2);
            cards.forEach(function (c, i) { c.classList.toggle('trad-ts2-card-active', i === ci); });
        }

        function applyWidths() {
            var pv = getPerView(wrap);
            maxIdx = Math.max(0, total - pv);
            var sw = wrap.querySelector('.trad-ts2-track-outer').offsetWidth / pv;
            slides.forEach(function (s) { s.style.width = s.style.minWidth = s.style.maxWidth = sw + 'px'; });
            if (current > maxIdx) current = maxIdx;
            track.style.transition = 'none';
            track.style.transform  = 'translateX(' + (-current * sw) + 'px)';
            requestAnimationFrame(function () { track.style.transition = ''; });
            buildDots();
            updateActiveCard(current);
        }

        function goTo(index) {
            var pv = getPerView(wrap);
            maxIdx  = Math.max(0, total - pv);
            current = Math.max(0, Math.min(index, maxIdx));
            var sw = wrap.querySelector('.trad-ts2-track-outer').offsetWidth / pv;
            track.style.transform = 'translateX(' + (-current * sw) + 'px)';
            updateDots(current);
            updateActiveCard(current);
        }

        function next() { goTo(current >= maxIdx ? 0 : current + 1); }
        function prev() { goTo(current <= 0 ? maxIdx : current - 1); }
        function startAuto() { stopAuto(); if (speed > 0) autoTimer = setInterval(next, speed); }
        function stopAuto()  { clearInterval(autoTimer); }

        btnNext && btnNext.addEventListener('click', function () { next(); stopAuto(); startAuto(); });
        btnPrev && btnPrev.addEventListener('click', function () { prev(); stopAuto(); startAuto(); });

        window.addEventListener('resize', function () {
            clearTimeout(resizeTimer);
            resizeTimer = setTimeout(applyWidths, 100);
        });
        applyWidths();
        startAuto();
    }

    function boot() {
        var el = document.getElementById(wrapId);
        if (el) { initTS2(el); return; }
        var obs = new MutationObserver(function () {
            var e = document.getElementById(wrapId);
            if (e) { obs.disconnect(); initTS2(e); }
        });
        obs.observe(document.body, { childList: true, subtree: true });
    }
    document.readyState === 'loading' ? document.addEventListener('DOMContentLoaded', boot) : boot();

    if (window.elementorFrontend) {
        window.elementorFrontend.hooks.addAction('frontend/element_ready/trad_testimonial_slider.default', function ($scope) {
            var w = $scope[0] && $scope[0].querySelector('.trad-ts2-wrapper');
            if (w) { w._ts2Inited = false; initTS2(w); }
        });
    }
}());
</script>
